version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trackme-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/trackme_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=@aahmhmm28
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: trackme-db
    restart: always
    environment:
      - POSTGRES_DB=trackme_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@aahmhmm28
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge