server:
  port: 8080

spring:
  application:
    name: TrackMe
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trackme_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:@aahmhmm28}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

jwt:
  secret: Gz1yS8hN3qU3bV5mT8pW2xY7sB9cD1jL4rP6nQ8oF2kT7mW5yZ9pC3kL6vM8xR1g2zW2a6J9K1sH6Y5R3cT2
  expirationMs: 3600000

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.data.mongodb: DEBUG

stripe:
  secret-key: "sk_test_51Qtm19I3zg9rkCm2Ks0t7RsOZn45OhjzNmHUg9CFReGLfTUo4Vg7UR3KPq1l2F2OWOK3FRNiGuJupkVRvsFCR3hz00ddW4ZLJw"